/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#213145",
        "on-primary-fixed-variant": "#372abf",
        "primary-fixed": "#e3dfff",
        "on-primary-fixed": "#100069",
        "on-surface-variant": "#464554",
        "inverse-primary": "#c3c0ff",
        "on-primary": "#ffffff",
        "surface-container": "#e5eeff",
        "tertiary-container": "#005e3f",
        "on-tertiary": "#ffffff",
        "surface-variant": "#d3e4fe",
        "on-error-container": "#93000a",
        surface: "#f8f9ff",
        "on-tertiary-fixed-variant": "#005236",
        error: "#ba1a1a",
        tertiary: "#00442d",
        background: "#f8f9ff",
        "tertiary-fixed": "#6ffbbe",
        "outline-variant": "#c7c4d7",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-highest": "#d3e4fe",
        "on-error": "#ffffff",
        "secondary-container": "#dce0e4",
        "surface-dim": "#cbdbf5",
        "primary-fixed-dim": "#c3c0ff",
        primary: "#2a14b4",
        "on-background": "#0b1c30",
        "on-primary-container": "#c1beff",
        "primary-container": "#4338ca",
        "inverse-on-surface": "#eaf1ff",
        outline: "#777586",
        "error-container": "#ffdad6",
        "surface-tint": "#5148d7",
        "surface-container-high": "#dce9ff",
        "on-surface": "#0b1c30",
        "surface-container-low": "#eff4ff",
        "on-tertiary-container": "#4ddda2",
      },
      fontFamily: {
        heading: ['"Plus Jakarta Sans"', "sans-serif"],
        body: ['"Atkinson Hyperlegible Next"', "sans-serif"],
      },
    },
  },
  plugins: [],
}
